name = "excel-labs"
compatibility_date = "2024-01-01"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "excel-labs-users"
database_id = "c36cfdef-ff3c-4c2c-bf3f-783e4e1d2103"

# Pages Configuration
pages_build_output_dir = "."
